env:
- ZMQ="git://github.com/zeromq/zeromq4-x.git"
before_install:
- git clone --depth 1 $ZMQ zmqlib
- cd zmqlib
- ./autogen.sh
- ./configure
- make
- sudo make install
- sudo /sbin/ldconfig
- cd ..
language: node_js
node_js:
  - stable
  - 4.2
  - 0.10
  - 0.12
addons:
  apt:
    packages:
      - uuid-dev
script: npm test
sudo: true
