sudo: required
dist: trusty
cache:
  apt: true
language: node_js
node_js:
  - stable
  - 4.2
before_script:
  - npm install -g tap
  - npm install -g codeclimate-test-reporter
  - npm install -d
after_success:
  - tap --coverage-report=text-lcov > ./lcov.info
  - codeclimate-test-reporter < ./lcov.info
addons:
  apt:
    packages:
      - libzmq3-dev
script: tap --cov tests/test.js
