sudo: required
dist: trusty
cache:
  apt: true
language: node_js
node_js:
  - stable
  - 4.2
before_script:
  - npm install -g tap
  - npm install -d
addons:
  apt:
    packages:
      - libzmq3-dev
script: tap tests/test.js
