sudo: required
dist: trusty
cache:
  apt: true
language: node_js
node_js:
  - stable
  - 4.2
before_script:
  - npm install -g codeclimate-test-reporter
  - npm install -g grunt-cli
  - npm install -d
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  apt:
    packages:
      - libzmq3-dev
script: npm test
